### ISSUE TITLE
Show the list of available versions on mouseover

### ISSUE THREAD

**Issue by Alphapage** [washanhanzi/crates-cmp#31]
Hello,

Great tool or workaround to dependi.
I was able to see the complete list of available versions when hovering a version and being able to choose one by clicking on it.

Is it a planned feature ?

Thank you in advance for your answer.

**Comment by washanhanzi** [comment]
Thanks for your interest in the project.

Unfortunately, I won't be able to work on this in the near future. I'm currently focused on completing a Rust refactor of the codebase.

**Comment by washanhanzi** [comment]
check https://github.com/washanhanzi/cargo-appraiser
