### ISSUE TITLE
Bright yellow text colors with "workbench.colorTheme": "Default Light+",

### ISSUE THREAD

**Issue by pragmatrix** [washanhanzi/crates-cmp#32]
Just tried to use version 0.0.51, but I'm getting some unexpected bright yellow colored text with the light+ color theme on macOS:

![image](https://github.com/user-attachments/assets/401d07c2-fad6-4f44-8f2f-f43db231f2f0)

**Comment by washanhanzi** [comment]
Thanks. fixed in 0.0.52.
